[package]
name = "piston-graphics_api_version"
version = "0.1.0"
authors = ["Sven Nilsen <bvssvni@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "graphics_api_version"

[dependencies]
